package subway.domain;

import org.springframework.data.domain.Persistable;

import javax.persistence.*;
import java.util.Objects;

/**
 * create table station (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * primary key (id)
 * )
 */
@Entity
public class Station implements Persistable<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @ManyToOne
    private Line line;

    protected Station() {
    }

    public Station(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void changeName(String name) {
        this.name = name;
    }

    public Line getLine() {
        return line;
    }

    public void setLine(Line line) {
        if (Objects.nonNull(line) && !line.getStations().contains(this)) {
            line.getStations().add(this);
        }
        this.line = line;
    }

    @Override
    public boolean isNew() {
        return false;
    }
}
